// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xityzenmiutolslacuvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpdHl6ZW5taXV0b2xzbGFjdXZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MzIwMjUsImV4cCI6MjA3MzAwODAyNX0.WU52FFsbHEzOfH4jbKzg13JPZ-najttdXvJkvrOQUNw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});